### PR TITLE
Update audience-activation.md

### PR DESCRIPTION
**Pull request by shiftedreality**
## Purpose of the pull request

This pull request (PR) ...

## Affected pages

- ...

### CODE REVIEW

**Comment by erikmarr** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
Something went wrong

**Review by erikmarr — APPROVED** [review]

**Comment by erikmarr** [comment]
@devops-devdocs import the pr

**Comment by dshevtsov** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
Something went wrong

**Comment by dshevtsov** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
@devops-devdocs imported this pull request

**Pull request merged**
