### PR TITLE
Deleted duplicated fragment of the "Admin session lifetime" section on the Session management page

### PR DESCRIPTION
**Pull request by rybkinevg**
## Purpose of the pull request

This pull request (PR) deletes the duplicated fragment of the "Admin session lifetime" section on the [Session management](https://experienceleague.adobe.com/en/docs/commerce-admin/systems/security/security-session-management) page.

## Affected pages

- https://experienceleague.adobe.com/en/docs/commerce-admin/systems/security/security-session-management#admin-session-lifetime

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@devops-devdocs import the PR

**Comment by jeff-matthews** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
Something went wrong

**Comment by devops-devdocs** [comment]
@devops-devdocs imported this pull request

**Pull request merged**
